### ISSUE TITLE
fanart not scrapped from allocine and alternate tmdb 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#210] opened 2015-05-18 05:28 UTC
with f1f133a and perhaps with some previous release, fanart aren't automatically scrapped from allocine and tmdb when new movie is added 
parameter: 
yamj3.sourcedb.scanner.movie=allocine
yamj3.sourcedb.scanner.movie.alternate=tmdb

what seems suspect :  
tmdb id isn't stored in db 
fanart isn't found - when i look at the tmdb site there is several fanart (backdrop) available

exemple  extract of the movie 'projet almanac': 
[06:59:07] DEBUG org.yamj.core.service.staging.StagingService  - New video file: T:\video\Film\Projet Almanac (2014) - 1080p.BluRay.x264.mkv
.....
[06:59:49] DEBUG org.yamj.core.tools.LanguageTools  - Scanning media file T:\video\Film\Projet Almanac (2014) - 1080p.BluRay.x264.mkv
[06:59:54] DEBUG org.yamj.core.service.ScanningScheduler  - Finished media file scanning
[06:59:54] INFO  org.yamj.core.service.ScanningScheduler  - Found 1 metadata objects to process; scan with 1 threads
[06:59:54] INFO  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning movie data for 'Projet Almanac' using allocine
[06:59:54] INFO  org.apache.http.impl.execchain.RetryExec  - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://api.allocine.fr:80: The target server failed to respond
[06:59:54] INFO  org.apache.http.impl.execchain.RetryExec  - Retrying request to {}->http://api.allocine.fr:80
[06:59:56] DEBUG org.yamj.core.service.metadata.online.OnlineScannerService  - Movie 566-'Projet Almanac', scanned OK
[06:59:57] DEBUG org.yamj.core.service.metadata.MetadataScannerService  - Updated movie in database: 566-'Projet Almanac'
[06:59:59] DEBUG org.yamj.core.service.ScanningScheduler  - Finished metadata scanning
.....
[07:00:19] DEBUG org.yamj.core.service.artwork.ArtworkProcessorService  - Process located artwork: ArtworkLocated [ID=12856, type=POSTER, source=allocine, url=http://fr.web.img3.acsta.net/pictures/15/01/13/11/55/541059.jpg]
[07:00:20] DEBUG org.yamj.core.service.file.FileStorageService  - Store file Projet Almanac_2014.movie.poster.2026853893.original.jpg; source url: http://fr.web.img3.acsta.net/pictures/15/01/13/11/55/541059.jpg
[07:00:20] DEBUG org.yamj.core.tools.web.PoolingHttpClient  - IO download host: http://fr.web.img3.acsta.net; rule: .*, maxRequests: 2
[07:00:25] DEBUG org.yamj.core.service.file.FileStorageService  - Store ARTWORK JPEG image: Projet Almanac_2014.movie.poster.2026853893.default-poster.jpg
[07:00:25] DEBUG org.yamj.core.service.artwork.ArtworkProcessorService  - Process located artwork: ArtworkLocated [ID=12857, type=POSTER, source=allocine, url=http://fr.web.img6.acsta.net/pictures/14/11/18/19/37/275486.jpg]
[07:00:25] DEBUG org.yamj.core.service.file.FileStorageService  - Store file Projet Almanac_2014.movie.poster.1848661623.original.jpg; source url: http://fr.web.img6.acsta.net/pictures/14/11/18/19/37/275486.jpg
[07:00:25] INFO  org.apache.http.impl.execchain.RetryExec  - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://fr.web.img6.acsta.net:80: The target server failed to respond
[07:00:25] INFO  org.apache.http.impl.execchain.RetryExec  - Retrying request to {}->http://fr.web.img6.acsta.net:80
[07:00:29] DEBUG org.yamj.core.service.file.FileStorageService  - Store ARTWORK JPEG image: Projet Almanac_2014.movie.poster.1848661623.default-poster.jpg
......
[07:00:39] DEBUG org.yamj.core.database.service.ArtworkLocatorService  - Found 0 local posters for movie Projet Almanac_2014
[07:00:39] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Scan online for poster: Artwork [ID=17341, type=POSTER, movie-id='Projet Almanac_2014']
[07:00:39] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Use tmdb scanner for Artwork [ID=17341, type=POSTER, movie-id='Projet Almanac_2014']
[07:00:39] DEBUG org.yamj.core.service.metadata.online.TheMovieDbScanner  - No TMDb id found for 'Projet Almanac', searching title with year 2014
[07:00:39] INFO  org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Found 1 potential matches for Projet Almanac (2014)
[07:00:39] DEBUG org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Checking Projet Almanac {2015)
[07:00:39] DEBUG org.yamj.core.service.metadata.online.TheMovieDbScanner  - No TMDb id found for 'Project Almanac', searching original title with year 2014
[07:00:39] INFO  org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Found 1 potential matches for Project Almanac (2014)
[07:00:39] DEBUG org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Checking Projet Almanac {2015)
[07:00:39] INFO  org.yamj.core.service.artwork.ArtworkScannerService  - No movie poster found for: Artwork [ID=17341, type=POSTER, movie-id='Projet Almanac_2014']
[07:00:39] DEBUG org.yamj.core.database.service.ArtworkLocatorService  - Found 0 local fanarts for movie Projet Almanac_2014
[07:00:39] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Scan online for fanart: Artwork [ID=17342, type=FANART, movie-id='Projet Almanac_2014']
[07:00:39] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Use tmdb scanner for Artwork [ID=17342, type=FANART, movie-id='Projet Almanac_2014']
[07:00:39] DEBUG org.yamj.core.service.metadata.online.TheMovieDbScanner  - No TMDb id found for 'Projet Almanac', searching title with year 2014
[07:00:40] INFO  org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Found 1 potential matches for Projet Almanac (2014)
[07:00:40] DEBUG org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Checking Projet Almanac {2015)
[07:00:40] DEBUG org.yamj.core.service.metadata.online.TheMovieDbScanner  - No TMDb id found for 'Project Almanac', searching original title with year 2014
[07:00:40] INFO  org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Found 1 potential matches for Project Almanac (2014)
[07:00:40] DEBUG org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Checking Projet Almanac {2015)
[07:00:40] INFO  org.yamj.core.service.artwork.ArtworkScannerService  - No movie fanart found for: Artwork [ID=17342, type=FANART, movie-id='Projet Almanac_2014']

**Comment by jluc2808** [comment] 2015-06-04 04:40
i get the same problem with Kingsman  Services secrets (2015) - 1080p.BluRay.x264.mkv

no fanart found with allocine and tmdb 
poster are found and stored
people are found (allocine filmography is always down, and tmdb filmography incomplet) 

only allocine id is stored : 198771  in yamj3 db 
tmdb id isn't stored 

if i add manually tmdb id : 207703
update is  proceeded but no update is performed  

[06:33:50] DEBUG org.yamj.core.service.metadata.MetadataScannerService  - Updated movie in database: 569-'Kingsman : Services secrets'
[06:33:53] DEBUG org.yamj.core.service.ScanningScheduler  - Finished metadata scanning
[06:34:34] INFO  org.yamj.core.api.json.FileController  - Updating file '1242'
[06:34:53] INFO  org.yamj.core.service.mediaimport.MediaImportService  - Process updated video 1242 - 'Kingsman Services secrets (2015) - 1080p.BluRay.x264.mkv'
[06:34:53] INFO  org.yamj.core.service.ImportScheduler  - Processed video stage file: 1242
[06:35:18] INFO  org.yamj.core.service.ScanningScheduler  - Found 1 media files to process; scan with 1 threads
[06:35:18] DEBUG org.yamj.core.tools.LanguageTools  - Scanning media file T:\video\Film\Kingsman Services secrets (2015) - 1080p.BluRay.x264.mkv
[06:35:23] DEBUG org.yamj.core.service.ScanningScheduler  - Finished media file scanning

**Comment by modmax** [comment] 2015-07-05 18:30
The problem is inside the TheMovieDB scanner, where no match is found for "Projet Almanac" on yoear 2014. It seems that this film is listed for 2015 in TMDB.

So I assign this bug to Omertron; perhaps he coulkd explain the behaviour.

It has nothing to do with setting of the scanners in YAMJ, cause the alternate scanner is not used, when allocine was successful.

**Comment by jluc2808** [comment] 2015-07-05 20:39
the problem is that allocine scanner is not complete and the 'succesfull' return is partial . 
i have several exemple with this issue, allocine is scrapped but without fanart or without plot , or without something else , alternate isn't used to complete the scanner and tmdb scanner never performed , because allocine scanner is considered as succesfull

**Comment by modmax** [comment] 2015-07-07 08:38
1.) You can tweak the behaviour of alternate scannimng by changing following configurations in the database.
yamj3.sourcedb.scanner.movie.alternate.always=false
yamj3.sourcedb.scanner.series.alternate.always=false
yamj3.sourcedb.scanner.person.alternate.always=false

If set to true, then the alternate scan will be done, even if normal scanner was successful.

2.) According to "movie scanner" vs. "poster scanner".
Both scanners for movie and poster always use the same mechanism to retrieve the ID of the movie database. But it may occur, that the title/year has been reset by a movie scanner, so that the poster scanner doesn't find anything .. but just for some scanners, for TMDB also the originalTitle is used for getting the movie database id.


Back to this issue:
It just seems, that the correct id could not be retrieved from TMDB, even if the title and original title ist used; but the given year does not match in this case.

**Comment by jluc2808** [comment] 2015-07-07 21:48
"If set to true, then the alternate scan will be done, even if normal scanner was successful."
 this not what i want to do, if successfull ==> because this will overwrite the primary info 
by exemple i don't want the tmdb plot but allocine plot (if tmdb is alternate) 
i want to start the alternate only if the scan is not complete 

back to the issue , if you are looking  with Kingsman Services secrets (2015) - 1080p.BluRay.x264.mkv the year is ok and the scanner doesn't take allocine fanart and plot

**Comment by modmax** [comment] 2015-07-07 22:24
No .. it won't overwrite the info from the main scanner; cause the "overwrite handling" defines a srategy which field will be overwritten with a content.

Example:
Allocine scans year correctly; so the overwrite flag of YEAR is set to allocine. If then the file is scanned with TMDB, then the ywar will not be touched, cause the normal behaviour is:
- first regard the NFO entries (cause created manually)
- then regard the 1st scanner info, if nothing else is set
- after that regard the 2nd scanner info, if nothing is set

Then the override mechanism (just like in YAMJ v2); and those information is stored in the database in tables like "videodata_override" or "person_override"; those tables contains informations which field has been set by whoch scanner. And an overriding mechanism decides (based on the set scanner, existing override flag and if the field is set at all), if a scanner can overwrite the cotent or not. This mechanism works; so right now, there is now issue.

Back to the issue:
I reopen it; perhaps I can investigate where the problem is.

**Comment by modmax** [comment] 2015-07-12 00:24
I close this issue, cause the configuration settings are known and working.

yamj3.sourcedb.scanner.movie.alternate.always=true
yamj3.sourcedb.scanner.series.alternate.always=true
yamj3.sourcedb.scanner.person.alternate.always=true

In that cases the alternate scanner will be used, even if main scanner was successful.
No values wil be overwritten by alternate scnaner, if already set by main scanner.

**Closed by modmax** 2015-07-12 00:24 UTC
Labels: bug, YAMJ-Core
