### ISSUE TITLE
update videodata status to 'DELETED' when files doesn't come from filescanner

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#328] opened 2017-08-11 18:20 UTC
Hello,

I'm was wondering why my deleted files were still displayed in my eversion skin.
even if a file has been deleted from the filesystem, and a new filescanner has been launch without exception, these file are still available from eversion (even if after a reboot of the popcorn hour).
I've check in the database and the status for these videodata is still as 'DONE'.
I think it would be 'DELETED' no?
regards

**Comment by jluc2808** [comment] 2017-08-12 06:23
i can't reproduce what you reported, 
if i delete a file from storage , next scan set the stage_file as deleted and the next delete task clean all the dependencies and the movie entry
if i set the file as deleted with bikini skin (clic the delete icon and hit the popup to confirm the file to delete) , the file is deleted the next time the delete task is running
if i let the filescanner to watch the folder and i delete a file the file is setted as deleted in the stage_file db

remarks:
if the movie or video are still in storage library (or the file with the movie name), each time the filescanner run, each time the entry is recreated in the db

**Comment by dav1170** [comment] 2017-08-14 02:55
Hello Jluc,

Thank for your feedback.

However, when I run a scan after a file has been deleted, its status doesn't change in db (according with my database knowledge), and the delete tasks seems not deleting any of the moviedata in state DELETED.

Additionnaly, I'm not able to delete from the bikini skin: when I click to the confirm button, nothing happens (firefox on linux).

Regards

**Comment by jluc2808** [comment] 2017-08-14 05:26
when you confirm a delete requestwith bikini, you should see in the jetty's log or windows if openned, the  api request asking jetty to change the status of the file ?
then the delete task will perform the delete job at the next run

**Comment by modmax** [comment] 2017-08-14 07:15
You should run the "StagingSanityTask". It checks every stage file if it is present or not.
Then the stage file will be marked as DELETED and the DeleteTask completly deletes those files.

**Closed by modmax** 2017-08-14 07:15 UTC

**Comment by modmax** [comment] 2017-08-14 07:16
The reason why a scan does not delete something is, that the file may be not available temporarly, i.e. if a usb drive contains the movies and is not connected.

**Comment by jluc2808** [comment] 2017-10-16 09:54
i will update bikini skin to add a selection within mediainfo popup to choose which stage_id file should be deleted for the detail movie displayed when there is more than one file for the same movie (now only the last one is available)
