### ISSUE TITLE
wrong movie scanned with NFO 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#158] opened 2014-12-18 22:47 UTC
scanned  nfo
< movie>
      < id moviedb="allocine">140623< /id>   // numéro d'identification du film sur ALLOCINE.  
      < id moviedb="tmdb">20352< /id>   // numéro d'identification du film sur Themoviedb.  
      < title>Moi, moche et méchant< /title>
      < titleSort>Moi, moche et méchant< /titleSort>
      < originalTitle>Moi, moche et méchant< /originalTitle>
< /movie>"
(i have added blank to post , but in the nfo there no blank  with < id) 

results: 
 "result": {
        "id": 568,
        "videoType": "MOVIE",
        "title": "Les Minions",
        "originalTitle": "The Minions",
        "videoYear": 2015,
        "plot": "A l'origine de simples organismes monocellulaires de couleur jaune, les Minions ont évolué au cours des âges au service de maîtres plus abjectes les une que les autres. Les disparitions répétitives de ceux-ci, des tyrannosaures à Napoléon, ont plongé les Minions dans une profonde dépression. Mais l'un d'eux, prénommé Kevin, a une idée. Flanqué de Stuart, l'adolescent rebelle et de l'adorable petit Bob, Kevin part à la recherche d'un nouveau patron malfaisant pour guider les siens. Nos trois Minions se lancent dans un palpitant voyage qui va les conduire à leur nouveau maître : Scarlet Overkill, la première superméchante de l'histoire. De l'Antarctique au New York des années 60, nos trois compères arrivent finalement à Londres, où ils vont devoir faire face à la plus terrible menace de leur existence : l'annihilation de leur espèce.",
        "country": "U.S.A.",

should return the contents from: 
http://www.allocine.fr/film/fichefilm_gen_cfilm=140623.html
or
http://www.themoviedb.org/movie/20352-despicable-me

but return the contents of http://www.allocine.fr/film/fichefilm_gen_cfilm=210493.html instead

**Comment by modmax** [comment] 2015-01-09 00:00
I've tested this example but I had no issue with this.

Please could you test:
1.) NFO same as file name
2.) nfo relation has been done
(select video data id from database and then select related nffo via
select * from nfo_relation where videodata_id=1;
)
3.) NFO stage file entry is DONE or ERROR or NOTFOUND?
4.) No parsing error for nfo
5.) Is there some log entries like:
Found allocine ID: 140623
Found tmdb ID: 20352
in the log file?

Can you retry this by first deleting the stage file
of video file and mkv (set to DELETED, wait until delete task has run (perhaps reset nextExecution for this task)) and then import the files via file scanner again.
Or (other approach): Set the videodata file to "UPDATED" and wait for rescan.

I cannot reproduce this problem but it seems that the NFO could not be determined as related
nfo to that video or failed to read the nfo file.

NOTE:
If you have the ran the filescanner on a NAS to which the computer, where the core is running on,
has no access to for reading files, or if the "stored directory path" (from point of view of the filescanner) ist different to the core's "point of view to the video/nfo file" (perhaps if the
directory paths are different). In those cases the NFO files cannot be read.
Then a mechanism should be used, where th NFO content is read from the filescanner and the content of the NFO is transferred to the core. But this is an future task.

**Comment by jluc2808** [comment] 2015-01-09 06:00
checked : 
1) nfo have the same name than the movie 
Moi moche et méchant - 1080p DTS.mkv
Moi moche et méchant - 1080p DTS.nfo
2) nfo_relation has been done - i have one entry in nfo_relation with the right videodata_id =568 and the right stage_file=7909
3) NFO stage_file entry is INVALID  
this the reason of the problem 

the nfo contents is (with blank to remove after the <)  - i will send you the nfo 
< movie>
      < id moviedb="allocine">140623</id>   // numéro d'identification du film sur ALLOCINE.  
      < id moviedb="tmdb">20352</id>   // numéro d'identification du film sur Themoviedb.  
      < title>Moi, moche et méchant</title>
      < titleSort>Moi, moche et méchant</titleSort>
      < originalTitle>Moi, moche et méchant</originalTitle>
< /movie>

the movie is under : 
/volume1/Media/video/Film/  
the nfo is under : 
/volume1/Media/video/Film/NFO/

the properties parameter are: 
yamj3.folder.name.nfo=NFO
yamj3.librarycheck.folder.nfo=true

the filescanner command executed under the synology NAS is: 
sh filescanner.sh -d /volume1/Media/video/NFO
tried too
sh filescanner.sh -d /volume1/Media/video/NFO/

**Comment by modmax** [comment] 2015-01-14 16:17
The status INVALID is set to a stage file if the file is not readable or doesn't exist.

If your running the file scanner from the NAS, then the path is the path seen from inside the NAS.
If the yamj3 core is running somewhere else (i.e. a windows server) where the NAS directories has been mounted per samba or NFS, then the path from the NAS is "/volume1/movies" but from Windows "X:/movies" ...

So the core cannot read the NFO file (which has only the path /volume1/movies) which unknown to windows and so the core.

**Comment by jluc2808** [comment] 2015-01-14 18:42
what i don't understand is the INVALID status because 
- the filescanner has been launched from the NAS 
sh filescanner.sh -d /volume1/Media/video/NFO

- the path is the path understable by the NAS (it's the one i'm using to navigate under the NAS shell) and isn't a windows path (x:/dir/dir)

- the directory_path stored under the stage_file is the one understable by the NAS :  /volume1/Media/video/NFO

- the jetty server is running under the NAS too , so should understand the path 

i'm missing something but i don't know what ?  

- the NFO contents looks ok (for me)

**Comment by modmax** [comment] 2015-01-14 23:51
This was an issue with the NAS and is now not reprodable anymore.
Some log messages were created to have the opportunity to evaluate the problem
if the error occurs again.

Right now there's nothing to do anymore.

**Closed by modmax** 2015-01-14 23:51 UTC
Labels: bug, wontfix, YAMJ-Core, YAMJ-FileScanner
